### ISSUE TITLE
实习：腾讯-WXG微信事业群-搜索应用部-模式识别中心-对话平台组

### ISSUE THREAD

**Issue by gelxgx** [wjq990112/Front-End-Recruitment#6]
## 北京 劳务实习生 前端开发

---

有意向的同学可以直接通过以下方式直接发送简历给我，简历评估过后即可安排面试~

- 微信：Gelx1015
- 邮箱：gelxgx@163.com 发送后请在此 issue 下滴滴我~

### 什么是劳务实习生？

---

在腾讯分为两种类型的实习生：

1. 日常实习生
   即通过官网渠道投递的日常实习生、留学生实习生或是通过校招后提前实习的实习生，工牌颜色为蓝色，享有腾讯全部福利，各方面待遇会更好一些，面试难度会相对较高。

2. 劳务实习生
   即部门急招、或通过非官方途径，例如：实习僧、boss 直聘等渠道进行招聘的实习生，工牌颜色为绿色，腾讯游戏体验待遇无法享受，实习薪资会稍低于日常实习生，面试难度会稍低。

### 我们正在做的事

---

### 搜索应用团队

致力于将人工智能领域技术应用到微信生态中，负责**微信看一看、搜一搜、微信朋友圈、小微对话机器人等业务**。为十多亿微信用户提供优质的内容和服务。我们的工作主要包括大规模分布式深度学习，自然语言处理，智能对话系统，数据挖掘，搜索和推荐引擎架构设计等。除此之外研发了包含数万台机器、数百万 CPU 的超大规模的计算、资源和任务调度平台。在前沿领域，我们也做了些探索性的尝试，推出了获得世界人工智能围棋大赛冠军的围棋 AI 引擎 PhoenixGo 并开源，另外也在国际权威对话系统竞赛 D5TC 获得冠军，提升微信在人工智能领域的影响力。

### 对话平台组

负责微信对话开放平台相关业务，主要以对话交互为核心, 为有客服需求的个人、企业和组织提供智能业务服务与用户管理能力的技能配置平台, 技能开发者可利用我们提供的工具自主完成客服机器人的搭建。可为小程序、公众号开发者提供快速对接微信 AI 语义的能力。

### 职位描述

1. 负责相关项目平台的前端开发工作
2. 负责持续优化前端页面性能和访问速度、提升页面体验
3. 负责前端框架建设、公共组件设计开发

### 岗位要求

1. 精通 CSS 样式，可按设计稿快速 1:1 实现 PC、H5、小程序界面开发
2. 熟练掌握使用 Vue、Vuex，有 React 和 Angular 经验加分
3. 熟悉微信小程序、小游戏的官方接口，有较好的学习新技术的能力
4. 有 Typescript、NodeJS 服务器端开发经验、熟练掌握 webpack 等其中的一项或多项
5. 乐观开朗可以快速融入团队，有较好沟通能力、抗压能力和服务意识，做事有自我驱动力。

**Comment by gelxgx** [comment]
> ### 北京 劳务实习生 前端开发
> 有意向的同学可以直接通过以下方式直接发送简历给我，简历评估过后即可安排面试~
> 
> * QQ：568742232
> * 微信： Gelx1015
> * 邮箱：[v_xanggong@tencent.com](mailto:v_xanggong@tencent.com) 发送后请在此issue下滴滴我~
> 
> #### 什么是劳务实习生？
> 在腾讯分为两种类型的实习生：
> 
> 1. 日常实习生
>    即通过官网渠道投递的日常实习生、留学生实习生或是通过校招后提前实习的实习生，工牌颜色为蓝色，享有腾讯全部福利，各方面待遇会更好一些，面试难度会相对较高。
> 2. 劳务实习生
>    即部门急招、或通过非官方途径，例如：实习僧、boss直聘等渠道进行招聘的实习生，工牌颜色为绿色，腾讯游戏体验待遇无法享受，实习薪资会稍低于日常实习生，面试难度会稍低。
> 
> ### 以下为职位描述，可供参考
> #### 我们正在做的事
> #### 搜索应用团队
> 致力于将人工智能领域技术应用到微信生态中，负责**微信看一看、搜一搜、微信朋友圈、小微对话机器人等业务**。为十多亿微信用户提供优质的内容和服务。我们的工作主要包括大规模分布式深度学习，自然语言处理，智能对话系统，数据挖掘，搜索和推荐引擎架构设计等。除此之外研发了包含数万台机器、数百万CPU的超大规模的计算、资源和任务调度平台。在前沿领域，我们也做了些探索性的尝试，推出了获得世界人工智能围棋大赛冠军的围棋AI引擎PhoenixGo并开源，另外也在国际权威对话系统竞赛D5TC获得冠军，提升微信在人工智能领域的影响力。
> 
> #### 对话平台组
> 负责微信对话开放平台相关业务，主要以对话交互为核心, 为有客服需求的个人、企业和组织提供智能业务服务与用户管理能力的技能配置平台, 技能开发者可利用我们提供的工具自主完成客服机器人的搭建。此小程序插件为小程序开发者提供快速对接微信AI语义的能力。
> 
> #### 职位描述
> 1. 负责相关项目平台的前端开发工作
> 2. 负责持续优化前端页面性能和访问速度、提升页面体验
> 3. 负责前端框架建设、公共组件设计开发
> 
> #### 岗位要求
> 1.精通CSS样式，可按设计稿快速1:1实现PC、H5、小程序界面开发
> 2.熟练掌握使用Vue、Vuex，有React和Angular经验加分
> 3.熟悉微信小程序、小游戏的官方接口，有较好的学习新技术的能力
> 4.有Typescript、NodeJS服务器端开发经验、熟练掌握webpack等其中的一项或多项
> 5.乐观开朗可以快速融入团队，有较好沟通能力、抗压能力和服务意识，做事有自我驱动力。

**Comment by oceanlvr** [comment]
滴滴😊

**Comment by wjq990112** [comment]
> 滴滴😊

加油，好好准备~

**Comment by gelxgx** [comment]
> 滴滴😊

哦豁，能麻烦同学加一下我微信重新发下简历嘛？
